services:
  - type: web
    name: rewards-app
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: GITHUB_TOKEN
        sync: false
